@startuml Diagram

skinparam Class {
    FontName Arial
    FontSize 15

    BorderColor DarkBlue
    BackgroundColor APPLICATION
    BorderThickness 3
    ArrowColor DarkBlue
    ArrowThickness 2
    HeaderBackgroundColor Aquamarine
}
skinparam MinClassWidth 200

enum AccountType <<enumeration>> {
    CORRIENTE
    AHORROS
}
class Bank {
    -name : String
    -code : String
    getName()
    setName(String)
    getCode()
    setCode(String)
    sendBalance(String, String, Double)
    addBankAccount(String, String, String, AccountType)
    searchBankAccount(String)
    validateBankAccount(String)

}
class BankAccount {
    -name : String
    -lastname : String
    -accountNumber : String
    -accountType : AccountType

    +getName()
    +setName(String)
    +getLastName()
    +setLastName(String)
    +getAccountNumber()
    +setAccountNumber(String)
    +getAccountType()
    +setAccountType(String)
    +consignBalance(Double)
    +withDrawBalance(Double)
    +compareBalanceTo(BankAccount)
    +sendBalance(BankAccount, Double)
}
left to right direction
Bank o-- BankAccount : +bankAccountList
Bank -->  AccountType
BankAccount -->  AccountType
@enduml