@startuml Diagrama Taller Herencia

skinparam Linetype ortho
skinparam style strictuml

class Banco {
    #nombre : String
    #direccion : String
    #codigo : String
    +Banco(nombre: String, direccion: String, codigo: String)

    +agregarCuentaAhorros(codigo: String, saldo: float, tasaAnual: float) : void
    +agregarCuentaCorriente(codigo: String, saldo: float, tasaAnual: float) : void
    +eliminarCuenta(codigo: String) : void
    +buscarCuenta(codigo: String) : Cuenta
    +validarCuenta(codigo: String) : boolean
}

abstract class Cuenta <<abstract>> {
    #codigo : String
    #saldo : float
    #numConsignaciones : int
    #numRetiros : int
    #tasaAnual : float
    #comisionMensual : float

    +Cuenta(codigo: String, saldo: float, tasaAnual: float)

    +consignarDinero(saldo: float) : void
    +retirarDinero(saldo: float) : void
    +calcularInteres() : void
    +extractoMensual() : void
}

class CuentaAhorros {
    +CuentaAhorros(codigo: String, saldo: float, tasaAnual: float)

    +estaActiva() : boolean
    +consignarDinero(saldo: float) : void
    +retirarDinero(saldo: float) : void
    +extractoMensual() : void
    +imprimir() : String
}
class CuentaCorriente {
    #sobregiro : float

    +CuentaCorriente(codigo: String, saldo: float, tasaAnual: float)

    +consignarDinero(saldo: float) : void
    +retirarDinero(saldo: float) : void
    +haySobregiro() : boolean
    +imprimir() : String
}
class CuentaException <<exception>> {
    +CuentaException(msg: String)
}
Banco " 1 " o--- " * " Cuenta : -listaCuentas

Cuenta ..> CuentaException : <<send>>
CuentaAhorros ..> CuentaException : <<send>>
CuentaCorriente ..> CuentaException : <<send>>

CuentaAhorros -right-|> Cuenta
CuentaCorriente -left-|> Cuenta
@enduml