@startuml Diagrama Taller Herencia

skinparam Linetype ortho
skinparam style strictuml

class Cuenta {
    #saldo : float
    #numConsignaciones : int
    #numRetiros : int
    #tasaAnual : float
    #comisionMensual : float

    +Cuenta(saldo: float, tasaAnual: float)
    +consignarDinero(saldo: float) : String
    +retirarDinero(saldo: float) : String
    +calcularInteres() : float
    +extractoMensual()
    +imprimir() : String
}

class CuentaAhorros {
    #estaActiva : boolean

    +CuentaAhorros(saldo: float, tasaAnual: float)
    +consignarDinero(saldo: float) : String
    +retirarDinero(saldo: float) : String
    +extractoMensual()
    +imprimir() : String
}
class CuentaCorriente {
    #sobregiro : float

    +CuentaCorriente(saldo: float, tasaAnual: float)
    +consignarDinero(saldo: float) : String
    +retirarDinero(saldo: float) : String
    +haySobregiro() : boolean
    +imprimir() : String
}
class CuentaException <<exception>> {
    CuentaException(msg: String)
}
Cuenta ..> CuentaException : <<send>>
CuentaAhorros .> CuentaException : <<send>>
CuentaCorriente .> CuentaException : <<send>>

CuentaAhorros -|> Cuenta
CuentaCorriente --|> Cuenta
@enduml