@startuml Diagrama

skinparam Linetype ortho
skinparam style strictuml

class CentroImpresion {
    +agregarDocumento(code: String, titulo: String, prioridad: int, contenido: String): void
    +agregarImpresora(code: String, estaConectada: boolean): void
    +eliminarDocumento(code: String) : void
    +eliminarImpresora(code: String) : void
    +buscarDocumento(code: String) : Documento
    +buscarImpresora(code: String) : Impresora
    +imprimirDocumento(): void
}

enum EstadoImpresora <<enumeration>> {
    ACTIVO
    INACTIVO
    MANTENIMIENTO
}

abstract class Impresora <<abstract>> {
    -code : String
    -marca : String
    +estaActiva() : boolean
    +agregarDocumento(code: String, titulo: String, prioridad: int, contenido: String): void
    +eliminarDocumento(code: String) : void
    +buscarDocumento(code: String) : Documento
    +<i>imprimirDocumento() : void
    -throwIfNotActive() : void
}

class Documento {
    -code : String
    -titulo : String
    -prioridad : int
    -fechaAgregado : LocalDateTime
    -fechaImpresion : LocalDateTime
    +estadoImpresion() : boolean
}

CentroImpresion " 1 " o-- " * " Documento : -listaDocumentos
CentroImpresion " 1 " *-- " * " Impresora : -listaImpresoras
Impresora " 1 " o-- " * " Documento : -listaDocumentos

Impresora ". 1 " --> EstadoImpresora : -estado
@enduml